
// This file is automatically generated. Do not modify.
'use client';

// This file is no longer used for local auth, but we keep it
// in case other Firebase services are added later.
export const FirebaseClientProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return <>{children}</>;
};
