// This file is automatically generated. Do not modify.
// For more information, see https://firebase.google.com/docs/web/learn-more#config-object

import { FirebaseOptions } from 'firebase/app';

// TODO: Replace this with your actual Firebase configuration.
const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  authDomain: "your-project-id.firebaseapp.com",
  projectId: "your-project-id",
  storageBucket: "your-project-id.appspot.com",
  messagingSenderId: "000000000000",
  appId: "1:000000000000:web:0000000000000000000000",
  measurementId: "G-XXXXXXXXXX"
};

export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig || !firebaseConfig.apiKey || firebaseConfig.apiKey === "AIzaSyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA") {
    console.warn("Using placeholder Firebase configuration. Please replace the placeholder in src/firebase/config.ts with your actual Firebase project configuration.");
  }
  return firebaseConfig;
}
