// This file is automatically generated. Do not modify.
import { initializeApp } from 'firebase/app';
import { getFirebaseConfig } from './config';

// Initializes Firebase and returns the app instance
export const initializeFirebase = () => {
  const firebaseConfig = getFirebaseConfig();
  return initializeApp(firebaseConfig);
};

export {
  FirebaseProvider,
  useFirebaseApp,
  useAuth,
  useFirestore,
  useFirebase,
} from './provider';

export { useUser } from './auth/use-user';
